### ISSUE TITLE
No track color

### ISSUE THREAD

**Issue by movepixels** [wangyi7099/vuescroll#1]
Hey,

Just giving this a try, I have it working but I can not get a track to have a color. The bar color I can set, but not the track / rail it sits on.

Code:
```
vRail: {
          width: '5px',
          pos: 'right',
          railBackground: '#009688',
          railOpacity: 0.5
        },
        vBar: {
          background: '#00bcd4', // cyan
          deltaY: 30,
          keepShow: false,
          opacity: 1
        },
```

Any ideas?

Thanks
Dave

**Comment by wangyi7099** [comment]
@movepixels 
Please update the newest version ! I have fixed this bug

**Comment by movepixels** [comment]
Still same result, no color.

"vuescroll": "^3.2.14",

Same vRail and vBar config as original post but no track color.

**Comment by movepixels** [comment]
Also noticed spelling error in your class naming.

vuesSrollContent =>  think you wanted vueScrollContent

**Comment by wangyi7099** [comment]
Sorry, I didn't  see the question  clearly,   eh..  before  you  use  the  track，  I  think  you  should set the track's opacity  first !  Because the opacity's default of the track is 0,  If you  don't set a opacity to the track, the track will not be seen anyway.

**Comment by wangyi7099** [comment]
@movepixels 
```javascript
vRail: {
          width: '5px',
          pos: 'right',
          background: '#009688',
          opacity: 0.5 // railOpacity to opacity
        },
        vBar: {
          background: '#00bcd4', // cyan
          deltaY: 30,
          keepShow: false,
          opacity: 1
        },
```
And in the latest version, I have changed the  `railOpacity ` to `opacity` , because I think the opacity is more easier to remember and spell compared to the  `railOpacity `  since I have separate the rail options and bar options, If this has any help? If you have any questions, welcome to response me.

**Comment by movepixels** [comment]
Looks good!
Thanks for the update.

Only one thing, I will live with it for now would be to allow a margin option for the rail and track. I liked a little buffer of 5px on the right which I simply override with a 
```
.vScrollbar{
  margin:5px 5px 5px 0;
}
```

But the track css is coded direct to the element so I cannot override the class so the track and rail do not line up but I will live with it.

Thanks

**Comment by movepixels** [comment]
Now the keepShow prop fails?

keepShow: false,

yet its always there even when nothing to scroll.

**Comment by wangyi7099** [comment]
@movepixels 

I just tested `keepShow` props, It seems work well... Have you assigned the right object? The `keepShow` property is only for the `scrollbars` , and if you want to hide the rail , please set the rail's opacity to 0 instead.   The options I just tested is:
```javascript
 ops: {
                        vBar: {
                            deltaY: 100,
                            keepShow: true
                        },
                        hBar: {
                            keepShow: true
                        },
                        vRail: {
                            pos:'right'
                        }
                    },
```    
If you have any questions, welcome to response me !

**Comment by wangyi7099** [comment]
@movepixels 

ps: If your mouse pointer is in the range of `scrollPanel` , the scrollbars will show anyway.
