### ISSUE TITLE
duplicate scrollbar on Firefox

### ISSUE THREAD

**Issue by emreed1** [wangyi7099/vuescroll#10]
Tried this in the latest Firefox quantum but the native scrollbar is still visible.

![capture](https://user-images.githubusercontent.com/357430/38653470-1aef13da-3e35-11e8-89ad-6aa3c12a0ea7.PNG)

**Comment by wangyi7099** [comment]
This is a bug, I'll fix it in recent release.

**Comment by wangyi7099** [comment]
@xusongfu 

```
 ops: {
 hBar: {
// 这里设置， 具体请看https://wangyi7099.github.io/VuescrollDocs/getStarted/zh/bar.html
}
}
```

**Comment by xusongfu** [comment]
您好，您可能误解我的意思了，我的意思是我的横向滚动条没办法显示出来，还是默认的滚动条，至于hBar设置，我看到文档了，我知道怎么设置的。

Best Wishes for you!

发件人: wangyi7099
发送时间: 2018年4月13日 18:48
收件人: wangyi7099/vuescroll
抄送: xusongfu; Mention
主题: Re: [wangyi7099/vuescroll] duplicate scrollbar on Firefox (#10)

@xusongfu
 ops: {
 hBar: {
// 这里设置， 具体请看https://wangyi7099.github.io/VuescrollDocs/getStarted/zh/bar.html
}
}

**Comment by wangyi7099** [comment]
@xusongfu 

试试最新的4.1版本

**Comment by cryptoji** [comment]
Hi, I'm using the vue scroll of 4.8.4 version.
But I can not know how to disable duplicate scrollbar on Firefox (v62.0)
@wangyi7099 Please you can check it?

<img width="1224" alt="2018-09-09 12 51 15" src="https://user-images.githubusercontent.com/25103900/45263287-29a5e280-b42f-11e8-9b83-8f794544b6f3.png">
<img width="1252" alt="2018-09-09 12 51 00" src="https://user-images.githubusercontent.com/25103900/45263290-2dd20000-b42f-11e8-8e60-ee7d797bdc11.png">

**Comment by wangyi7099** [comment]
@cryptoji 
Hi! I'm using FireFox v62.0 too. But works for me. 
![Uploading 屏幕快照 2018-09-09 下午6.13.28.png…]()

**Comment by wangyi7099** [comment]
@cryptoji 
Hi! I'm using FireFox v62.0 too. But works for me. 
<img width="1290" alt="2018-09-09 6 13 28" src="https://user-images.githubusercontent.com/24426655/45263467-5b816e00-b45c-11e8-848c-3d5e8b2d32ca.png">

**Comment by cryptoji** [comment]
Hmm...
As I understand it is the system OSx scroll, it is customized through the pseudo-elements of the css, but it only works for safari / chrome + all operating systems that do not add the system scrolls to the browsers :(

**Comment by wangyi7099** [comment]
No, it is customized by adding `margin-right` and `calc(100%)` + native scrollbar size. You can open the browser and inspect the . `.__panel` element, you can see the style `margin-right: -15px` and `cal(100% + 15px)` on it. And the `15px` is the native scrollbar's size.  And if you get rid of the style on Dev-Tool, you will see the native scrollbar immediately, This is how vuescroll customizes the scrollbars.

<img width="1271" alt="2018-09-09 6 37 31" src="https://user-images.githubusercontent.com/24426655/45263658-12331d80-b460-11e8-9c33-d949e53b8c0e.png">

**Comment by cryptoji** [comment]
👏 thank you so much, friend
it's very pleasant that you react so quickly and understand this)

**Comment by wangyi7099** [comment]
You are welcome, so glad you can understand!

**Comment by DineshSrisrimal** [comment]
I faced the same issue and fixed by adding the following CSS. Hope it helps peeps.
```
.__hidebar {
    -ms-overflow-style: none; /* IE 11 */
    scrollbar-width: none;
  }
```
