### ISSUE TITLE
不能通过参数控制只显示x或是y滚动条吗？

### ISSUE THREAD

**Issue by werbug** [wangyi7099/vuescroll#11]
scrollpanel 只是加个overflow：scroll，能分项加overflow-x,或overflow-y不

**Comment by werbug** [comment]
opacity: 0可以隐藏，但是在ie,火狐下就GG啦

**Comment by werbug** [comment]
对的是这个意思

**Comment by wangyi7099** [comment]
好的。   我会在下个版本进行支持。
