### ISSUE TITLE
scrollingX 设置为false的时候vuescroll-panel的height不应该为calc(100% + 17px)应该是100%

### ISSUE THREAD

**Issue by werbug** [wangyi7099/vuescroll#14]
![qq 20180419152610](https://user-images.githubusercontent.com/22109741/38977274-7a3b59b4-43e6-11e8-9a1b-8a6d2f9fe38e.png)
参数设置：
 ops: {
        scrollPanel: {
          scrollingX: false,// false to diable
          scrollingY: true // false to diable
        },  
}
问题：
scrollingX 设置为false的时候vuescroll-panel的height不应该为calc(100% + 17px)应该是100%

**Comment by wangyi7099** [comment]
感谢！！！
