### ISSUE TITLE
官方文档页面不能下拉

### ISSUE THREAD

**Issue by Abigale-ztg** [wangyi7099/vuescroll#18]
https://wangyi7099.github.io/VuescrollDocs/getStarted/zh/usage.html
页面下拉不了,文档看不全

**Comment by wangyi7099** [comment]
这个官方文档使用的是vuescroll早期的版本，是存在这个bug的， 未来一周内会发布新的基于vuepress的文档~

**Comment by wangyi7099** [comment]
好了 刚发布了4.5.0版本 已经修复了~
