### ISSUE TITLE
On trackpad (Macbook Pro, OS X High Sierra), scrolls way too fast

### ISSUE THREAD

**Issue by mekhami** [wangyi7099/vuescroll#2]
Using a trackpad scrolls the scrollbar unusably fast on a macbook, os x high sierra.

**Comment by wangyi7099** [comment]
@mekhami  
Hi,boy!  I don't have a mac book at this time,  do you have any idea? welcome pr!

**Comment by mekhami** [comment]
I'm sorry was this resolved? Why was this closed?

**Comment by wangyi7099** [comment]
@mekhami  I just update the code,   does it work now? I'm sorry I don't have a mac book now,  so perhaps can't test your problem...

**Comment by wangyi7099** [comment]
@mekhami 
Hi! Are you here? I have updated the latest version, can you have a try to test whether it works or not?

**Comment by mekhami** [comment]
hi, i will test tomorrow and report for you.

**Comment by wangyi7099** [comment]
Close this issue until you give a report.
