### ISSUE TITLE
现在更新比较频繁,想问一下什么时候会推出稳定版本

### ISSUE THREAD

**Issue by Abigale-ztg** [wangyi7099/vuescroll#21]
谢谢开源.

**Comment by wangyi7099** [comment]
用的人多了 提的需求/bug多了 自然就会稳定起来。 一个产品是需要经过不断的迭代的。 
目前版本的vuescroll的话， 常规状态下应该算是比较稳定可以使用了，如果再加上ssr服务端渲染什么的那就不好说了。 可以会有一些小的瑕疵， 但是大体上应该没问题了。

**Comment by wangyi7099** [comment]
总的来说得需要bug数的堆。

**Comment by wangyi7099** [comment]
现在差不多了。
