### ISSUE TITLE
No scroll in Firefox

### ISSUE THREAD

**Issue by arkhenstone** [wangyi7099/vuescroll#22]
Firefox 59, Linux.

Going to the demo page, you can't scroll, and you don't see any scroll coming from Vue-scroll. Works fine in Chromium Linux.

**Comment by wangyi7099** [comment]
Perhaps because the vue-server-side rendering. run the demo folder of this repo in FireFox works well.

**Comment by arkhenstone** [comment]
Okay it works well on demo pages. But still, it is frustrating that your demo page is not working on a browser, and one of the most used one. Especially when the page doesn't say a word about the difference of native vs vuescroll. So maybe write a bit on the page, and set a warning on the demo page that if it doesn't work, they might try the demo pages from this repo.

**Comment by wangyi7099** [comment]
Thanks for your advice. But I give a comparison between native and vuescroll in

**Comment by arkhenstone** [comment]
It's a different issue that may not be there, you can close it for now :) 

What I suggest is not an issue by it, and the example shows pretty well what is Vue scroll. Might be a bit more precise via text, if you remove examples, you don't know what vue scroll adds to your project, but features names of what native don't do, without any explanation of what vuescroll actually does. But not anything near important as long examples works now.

**Comment by wangyi7099** [comment]
Thanks, I will close it now.
