### ISSUE TITLE
发现一个体验非常差的地方,希望改进

### ISSUE THREAD

**Issue by Abigale-ztg** [wangyi7099/vuescroll#23]
环境:chrome55
描述:
鼠标mousedown的时候移动bar,有时候可能移动的不是那么水平或者垂直,导致鼠标小手的图标变成禁止的图标,这时鼠标移动,滚动条不动.然后鼠标mouseup,就可以控制滚动条的移动.体验非常不好,我已经出现过很多次这种操作了.

**Comment by wangyi7099** [comment]
好的😄谢谢你的建议  我会改进

**Comment by wangyi7099** [comment]
现在请再试一下

**Comment by Abigale-ztg** [comment]
可以了,谢谢

**Comment by wangyi7099** [comment]
@Abigale-ztg 
那我就关闭这个issue了😁
