### ISSUE TITLE
上拉加载更多必须要设置mode: 'slide'吗

### ISSUE THREAD

**Issue by zhij** [wangyi7099/vuescroll#30]
设置了mode: 'slide'后，样式会有问题。<div class="vuescroll-panel" style="position: relative; display: inline-block; transform-origin: left top 0px; user-select: none; box-sizing: border-box; transform: translate3d(0px, 0px, 0px) scale(1);">
display: inline-block; 怎么改成display: block;

**Comment by wangyi7099** [comment]
@zhij 
你好， slide模式是可以设置成display:block的， 关于设置成display-block问题我已在这个版本`native`模式改了，但是忘了在`slide`模式下改，所以下个版本会修复。 最迟晚上。

**Comment by wangyi7099** [comment]
已经在4.5.27版本改成`display: block;`了

**Comment by zhij** [comment]
@wangyi7099 ok,thanks
