### ISSUE TITLE
class="vuescroll-panel"为什么要加上width:-webkit-fit-content?

### ISSUE THREAD

**Issue by zhij** [wangyi7099/vuescroll#32]
mode: 'slide'的时候，4.5.27修复了display: inline-block的问题，但是又多了个width:-webkit-fit-content，导致class="vuescroll-panel"下面的子元素（div）撑不开

**Comment by wangyi7099** [comment]
是这样的，是为了能检测到子元素resize事件，现在最新的已经改为子元素宽度不足100%时用100%，超过则用fit-content。还没来得及发布。

**Comment by wangyi7099** [comment]
试试最新的4.5.31版本。。。

**Comment by zhij** [comment]
谢谢，这个问题解决了。不过还有个问题想问下，在做PC端上拉加载更多的时候，需要按住鼠标，然后滚轮才能加载，有没有办法可以像普通的scroll事件一样，滚轮直接加载呢😊

**Comment by wangyi7099** [comment]
监听`handle-scroll`事件， 传入的参数里有个process。。 可以检测到你滚动的进程。 当`process`为`1`的时候，说明滚动到底部了， 在那个时候加载数据应该能行吧。。

**Comment by wangyi7099** [comment]
如果你想显示动画的那种加载，也可以，不过还没有那个公共的对外API，只在vuescroll内部使用到，如果你需要的是那种加载的话，我可以把它写成公共的api方便调用。。。

**Comment by wangyi7099** [comment]
已经实现 参照[triggerrefreshorload](https://wangyi7099.github.io/vuescrolljs/zh/guide/api.html#triggerrefreshorload-4-5-32)...
