### ISSUE TITLE
列表为ajax返回数据，initialScrollY 该配置项为100%，不生效

### ISSUE THREAD

**Issue by Ltecure** [wangyi7099/vuescroll#33]
version：4.5.27
```
<vue-scroll :ops="msgOps" ref="vs">
     <ul class="msglist">
           <msg-list v-for="(item, idx) in msglist" :key="idx"
                            :item="item"></msg-list>
     </ul>
</vue-scroll>
```
msglist为动态内容时，initialScrollY 该配置项为100%，偶尔生效，偶尔不生效。
我试着在API scrollTo 中通过vm.$nextTick 设置，依旧不生效。
不知道是不是我这样使用有问题

**Comment by Ltecure** [comment]
嗯，我试着在回调函数中使用，是可以的，但不能保证到最底部。用vue可以写在 vm.$nextTick里面。谢谢

**Comment by wangyi7099** [comment]
回掉函数里也得在nextTick里面滚动数据。 因为刚刚给data数据赋值dom是不会立刻改变的。

**Comment by freecodemans** [comment]
这个问题再ios的时候也ok吗
