### ISSUE TITLE
在HBuider的内置浏览器中报错，打包成APP后，滚屏功能失效，但在高版本chrome浏览器中使用正常

### ISSUE THREAD

**Issue by no7cat** [wangyi7099/vuescroll#4]
我用<script src=>方式引入你的vuescroll但在HBuider的内置浏览器中总是报错，说
[Web浏览器] "Uncaught TypeError: undefined is not a function"	/js/vuescroll.js (632)，同样的代码在chrome 版本 66.0.3343.4（正式版本）上不会出错。我找不到问题是出在哪？可否邮件指点一下？我有需要在HB的内置浏览器通过。

**Comment by no7cat** [comment]
rinke@qq.com

**Comment by wangyi7099** [comment]
@no7cat  好的，我下个HBuider看一下。 目前确实没有在app里做过测试， 我会尽快修复这个bug。
