### ISSUE TITLE
api scrollTo 在单页面组件中怎么使用？

### ISSUE THREAD

**Issue by werbug** [wangyi7099/vuescroll#5]

**Comment by wangyi7099** [comment]
假设有以下div元素, 可以给vuescroll加一个ref属性，然后通过ref来调用vuescroll里的方法scrollTo：
```html
 <div class="parent">
<vue-scroll ref="vs">
</vue-scroll>
</div>
```
然后在你的method里：
```javascript
 methods: {
  scrollTo() {
  this.$refs['vs'].scrollTo({x: 10, y:10})   // 让内容滚动到x:10 y:10 的位置， 也可以只传一个参数。
}

}
```
这样就差不多了， 对了， 还可以在scrollPanel配置项里设置滚动的动画， 详见
https://github.com/wangyi7099/vuescroll/blob/5ec457e6e51e61024c6991be51484c821a08bcff/src/util/index.js#L172

有什么不懂的欢迎提出~

**Comment by werbug** [comment]
谢谢解答
