### ISSUE TITLE
scrollContent padding set to false doesn't work

### ISSUE THREAD

**Issue by tochoromero** [wangyi7099/vuescroll#6]
I have a super basic scroll, the only setting I'm applying is:
```
ops: {
     scrollContent: {
     padding: false
   }
 }
```

The problem is that it doesn't get rid of the padding.
I can change other settings and see its effects, so I know I'm setting the `ops` correctly, it just seems the `padding` setting is being ignored.

**Comment by wangyi7099** [comment]
I'm on the  train, and I'll report to you on afternoon or later.

**Comment by wangyi7099** [comment]
Just fixed!

**Comment by tochoromero** [comment]
That was quick, thank you!

**Comment by tochoromero** [comment]
Is there a release with this fix?

**Comment by wangyi7099** [comment]
Thank you for you replay! I'm  preparing a feature release in recent day😄
