### ISSUE TITLE
打包过后为什么会自动加上margin-bottom,margin-right,height？

### ISSUE THREAD

**Issue by werbug** [wangyi7099/vuescroll#9]
![qq 20180411181644](https://user-images.githubusercontent.com/22109741/38610812-8d0410e6-3db4-11e8-9d3a-72cea0ef2c85.png)

**Comment by wangyi7099** [comment]
额。。 最新版的已经把这个给去掉了。 当初加上这个是为了隐藏系统默认的滚动条。

**Comment by werbug** [comment]
这样啊，谢谢

**Comment by wangyi7099** [comment]
@werbug  貌似又得加上了， 因为直接隐藏隐藏滚动条在firefox下不起作用。 所以得给margin-top一个负值来达到隐藏滚动条的效果了。
